version: 1

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src/OPC.PowerApps.DataMigration"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"