# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
- task: bool.update-assembly-info.update-assembly-info-task.update-assembly-info@2
  displayName: 'Update Assembly Info'
  inputs:
    company: 'OPC-CPVP'
    assemblyVersionBuild: '$(Build.BuildId)'

- task: kherzog.AssemblyInfoReader.assembly-info-reader-build-task.AssembyInfoReader@2
  displayName: 'Generate Variables from Assembly Info'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '$(Parameters.solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet pack - Pre-Release'
  inputs:
    command: custom
    arguments: 'pack $(Build.SourcesDirectory)\src\OPC.PowerApps.DataMigration\OPC.PowerApps.DataMigration\OPC.PowerApps.DataMigration.csproj -OutputDirectory $(Build.ArtifactStagingDirectory) -Properties "Configuration=$(BuildConfiguration)" -Version $(AssemblyInfo.AssemblyVersion.Major).$(AssemblyInfo.AssemblyVersion.Minor).$(AssemblyInfo.AssemblyVersion.Build) -Suffix beta'

- task: NuGetCommand@2
  displayName: 'NuGet pack - Release'
  inputs:
    command: custom
    arguments: 'pack $(Build.SourcesDirectory)\src\OPC.PowerApps.DataMigration\OPC.PowerApps.DataMigration\OPC.PowerApps.DataMigration.csproj -OutputDirectory $(Build.ArtifactStagingDirectory) -Properties "Configuration=$(BuildConfiguration)" -Version $(AssemblyInfo.AssemblyVersion.Major).$(AssemblyInfo.AssemblyVersion.Minor).$(AssemblyInfo.AssemblyVersion.Build)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()