# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines/*
    - src/*
    exclude:
    - azure-pipelines/README.md

pr: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
- task: bool.update-assembly-info.update-assembly-info-task.update-assembly-info@2
  displayName: 'Update Assembly Info'
  inputs:
    company: 'OPC-CPVP'
    assemblyVersionBuild: '$(Build.BuildId)'

- task: kherzog.AssemblyInfoReader.assembly-info-reader-build-task.AssembyInfoReader@2
  displayName: 'Generate Variables from Assembly Info'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    vsVersion: 15.0
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'Test Assemblies'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet pack - Pre-Release'
  inputs:
    command: 'custom'
    arguments: 'pack $(Build.SourcesDirectory)\src\OPC.PowerApps.DataMigration\OPC.PowerApps.DataMigration.nuspec -OutputDirectory nupkgs\pre-release -Properties "Configuration=$(BuildConfiguration)" -Version $(AssemblyInfo.AssemblyVersion.Major).$(AssemblyInfo.AssemblyVersion.Minor).$(AssemblyInfo.AssemblyVersion.Build) -Suffix beta'

- task: NuGetCommand@2
  displayName: 'NuGet pack - Release'
  inputs:
    command: custom
    arguments: 'pack $(Build.SourcesDirectory)\src\OPC.PowerApps.DataMigration\OPC.PowerApps.DataMigration.nuspec -OutputDirectory nupkgs\release -Properties "Configuration=$(BuildConfiguration)" -Version $(AssemblyInfo.AssemblyVersion.Major).$(AssemblyInfo.AssemblyVersion.Minor).$(AssemblyInfo.AssemblyVersion.Build)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
      **\nupkgs\**
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
